#!/bin/sh
SHUTUP=""

cc $SHUTUP -o b -g -Wall -Wextra -Wno-parentheses -Wno-implicit-fallthrough -I.. -I. ../b.c out.c


STUFF='brt2.s printn.s printf.s libb.s bilib.s'

# compile B compiler with the C-B-compiler
echo compile bc_c
cat ../bc.b | preproc.sh > bc_x.b
bb bc_x || exit 1
rm bc_x.s
mv a.out bc_c
echo compile ba_c
bb ba || exit 1
rm ba.s
mv a.out ba_c

# now compile B compiler built with the previous compiler
echo compile bc_b with bc_c
bc_c bc_x.b bc.i || exit 1
ba_c bc.i bc.s || exit 1
cc -o bc_b -g brt1.s bc.s $STUFF
echo compile ba_b with bc_c
bc_c ba.b ba.i || exit 1
ba_c ba.i ba.s || exit 1
cc -o ba_b -g brt1.s ba.s $STUFF

# now compile B compiler with itself
# this concludes the magic
echo compile bc_b with bc_b
bc_b bc_x.b bc.i || exit 1
ba_b bc.i bc.s || exit 1
cc -o bc -g brt1.s bc.s $STUFF
echo compile ba_b with ba_b
bc_b ba.b ba.i || exit 1
ba_b ba.i ba.s || exit 1
cc -o ba -g brt1.s ba.s $STUFF

rm bc.i bc.s ba.i ba.s
